Feature branch
prg-04/Hello-World-Project pull request #1
Opened 2022-08-16 21:32 UTC by prg-04

Initialized the Hello World webpage and change the h1 element color to chartreuse

2022-08-16 22:10 UTC, BenMukebo requested changes
### Hi @prg-04,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻

- Github flow was correctly used.  ✔️    
- There is a .gitignore file listing test.md file and node_modules directory.  ✔️ 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

- [ ] Please, Write a meaningful title for your pull request and always add a short summary of changes introduced in the pull request. you can check the  [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md#:~:text=basic%20rules%20to%20follow%20in%20Microverse%20projects)
eg: 
```
## In this Milestone, I have done the following step to set up a "Hello world" repository:

- [ ] Create a new GitHub repo.
- [ ] Add a `.gitignore` file.
- [ ] Set up [a linter for HTML and CSS](https://github.com/microverseinc/linters-config).
- [ ] Make sure that any files that are not relevant are ignored by git.
- [ ] Add a descriptive README file ....

```

- [ ] Kindly, Add a descriptive README file to your project,  A professional README file should have a project title, project description, list of technology used in the project, instructions to set the project up locally as this will be of help to non-technical users.  this includes `git clone URL` , `cd project_name`, etc, you can copy and paste the content but remember to customize it to your project

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


- [OPTIONAL ] Kindly, make to use descriptive commit messages. Each commit message should be written in the imperative tense and always `capitalized`. [Read more about how to write descriptive commit messages](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md#:~:text=Use%20descriptive%20commit%20messages%20%2D%20each%20commit%20should%20be%20small%20enough%20to%20describe%20it%20in%20one%20sentence.%20The%20commit%20message%20should%20be%20written%20in%20the%20imperative%20tense%20and%20capitalized)

Example:
  - :x: Wrong: added Descriptive README
  - :heavy_check_mark: Right: Add descriptive README 
 
Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-16 22:10 UTC, BenMukebo commented on index.html
> +    <h1>Hello Microverse!</h1>
- [ ] According to the project requirements 👇🏻, the style.css file should include one class with styles for your header `h1` (make it in your favorite color). Kindly add this 

![15](https://user-images.githubusercontent.com/79058364/184992901-0f5bb6a2-14bf-46c2-863b-bef56fe020bc.png)

2022-08-17 09:48 UTC, topeogunleye requested changes
Hi @prg-04, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Try-Again](https://user-images.githubusercontent.com/52934128/180646051-aed7efa6-6d15-4853-9962-73186e366f2c.gif)

> ## (Highlights) Good Points: 💪 
> * Good commit messages. :heavy_check_mark:
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
> * Professional README file. :heavy_check_mark:
> * PR has a good title and summary :heavy_check_mark:

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
>- [ ] From now on, I kindly suggest that you please make use of imperative mood in the subject line for your commit messages.
:x: Bad Commit Messages
![image](https://user-images.githubusercontent.com/52934128/185089065-bc1dfe5b-8312-47c4-bfa4-ed0171463d54.png).png)
> ### Good Commit Messages:
✔️  Add fix for dark mode toggle state
✔️  Update README file.
✔️  Add styles to h1.
>
- [ ] Please refer to this article: please read it and apply it in your work from now on: [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md);

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your @topeogunleye so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-17 09:48 UTC, topeogunleye commented on index.html
> +    <h1>Hello Microverse!</h1>
- [ ] As suggested by the previous code reviewer, I kindly suggest that you add a class selector and use in to style your `h1` instead of the element selector you used.

`  <h1 class="header">Hello Microverse!</h1>`

2022-08-17 15:34 UTC, merged